package com.annotations;

import java.lang.annotation.Documented;

/**
 * 
 * @author pardeshi_n
 * Indicates that new annotation should be included into java documents 
 * generated by java document generator tools.
 */

@Documented
public @interface MyCustAnnoteDocumented {

}
